### PR TITLE
DOCS: Warn that Python 3.11 is not supported

### PR DESCRIPTION
**Pull request by SamSaffron**

### CODE REVIEW

**Comment by SamSaffron** [comment]
It currently goes into a tailspin in 3.11 due to pytorch... to save people time adding a note to the readme may help.

**Review by brycedrennan — APPROVED** [review]

**Comment by brycedrennan** [comment]
Thanks! The latest version is supposed to prevent the attempt. 
https://github.com/brycedrennan/imaginAIry/blob/master/setup.py#L110

Wonder what happened. Welcome any additional info you have about the environment and version you were installing.

**Comment by SamSaffron** [comment]
Howdy Bryce, 

Yeah I am certainly not a Python expert so treat everything I say with many grains of salt... 

I am on Arch, Python version 3.11.3 

The problem is that pip install in this case takes an enormous amount of time somehow on my install just to end up failing. Is there any chance that pip in 3.11 just chooses one of the earlier version that "did" support that version of python. Ideally ... what should happen on 3.11 is that it does not dependency download at all ... just says sorry ... use a diff version.

**Comment by brycedrennan** [comment]
Oh I see. I think you're exactly right. I should remove the python_requires attribute and just have it throw an error as described.  This type of problem is discussed here:
https://discuss.python.org/t/requires-python-upper-limits/12663/73

**Pull request merged**
