### PR TITLE
Automatic changelog on release

### LINKED ISSUE #147: Automatic changelog
Are you interested in an automatic generated change log for a new release ?
If yes, I could make a pull request

### PR DESCRIPTION
**Pull request by hannesa2**
Simply push a git tag and you are done.

Here you see a simple test release https://github.com/hannesa2/imaginAIry/releases/tag/7.3.0-test with just one empty pull request

close #147

### CODE REVIEW

**Comment by brycedrennan** [comment]
But it doesn't update the version in setup.py or produce the wheels. 

I suppose this will work with the existing flow though? I'll make my commit in master and then  push a git tag.

**Comment by hannesa2** [comment]
> But it doesn't update the version in setup.py or produce the wheels.

As the title says "Automatic changelog on release ". No update or produce of something. If it's a desired behavior it could be done in an additional pull request 
 
> I suppose this will work with the existing flow though? I'll make my commit in master and then push a git tag.
Only pull requests will be mentioned. Direct push to master will be ignored

**Comment by hannesa2** [comment]
> ... or produce the wheels.

I've no clue how to do this

**Comment by brycedrennan** [comment]
I think i can make this work with wheels. Haven't had a chance to do so yet
.

**Comment by brycedrennan** [comment]
closing for now

**Pull request closed without merging**
