### PR TITLE
fixed VRAM leak with none-OOP

### PR DESCRIPTION
**Pull request by h4rk8s**
Just an idea and a temporary solution. So far on my GTX 1080 Ti, I've run more than 100 images through the test, and a total of 8GB VRAM is stable at the top of 6GB VRAM 👇. 

Snapshot 2022-09-28 at 00 03 07@2x

This code isn't formatted, and only the --fix-face is changed. Theoretically, --upscale needs to be changed too. This is perfect, so close the merge. Thank you very much!

### CODE REVIEW

**Comment by brycedrennan** [comment]
Great work. thank you!  I'll take a look at this in the evening (6 hours from now)

**Comment by h4rk8s** [comment]
> Great work. thank you! I'll take a look at this in the evening (6 hours from now)

@brycedrennan  I found that although the memory leak was fixed, the image was no longer bright after generation. I needed some time to look at it again.
Snapshot 2022-09-28 at 08 42 00@2x

**Comment by brycedrennan** [comment]
I'm impressed you thought to check the image output.  With your help I was able to find the cause and create a remedy in #32 that didn't have as much of a refactor.

**Comment by h4rk8s** [comment]
> 

As a Python programmer, I have been paying attention to this field. I am very impressed by your pure command line implementation method, which is the main method I use now. We will communicate with you later if we have new ideas.

**Comment by brycedrennan** [comment]
thanks!

**Pull request closed without merging**
